export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCT_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCT_SUCCESS'
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCT_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const ADMIN_PRODUCTS_REQUEST = 'ADMIN_PRODUCTS_REQUEST'
export const ADMIN_PRODUCTS_SUCCESS = 'ADMIN_PRODUCTS_SUCCESS'
export const ADMIN_PRODUCTS_FAIL = 'ADMIN_PRODUCTS_FAIL'

export const CREATE_PRODUCTS_REQUEST = 'CREATE_PRODUCTS_REQUEST'
export const CREATE_PRODUCTS_SUCCESS = 'CREATE_PRODUCTS_SUCCESS'
export const CREATE_PRODUCTS_FAIL = 'CREATE_PRODUCTS_FAIL'
export const CREATE_PRODUCTS_RESET = 'CREATE_PRODUCTS_RESET'

export const DELETE_PRODUCTS_REQUEST = 'DELETE_PRODUCTS_REQUEST'
export const DELETE_PRODUCTS_SUCCESS = 'DELETE_PRODUCTS_SUCCESS'
export const DELETE_PRODUCTS_FAIL = 'DELETE_PRODUCTS_FAIL'
export const DELETE_PRODUCTS_RESET = 'DELETE_PRODUCTS_RESET'

export const UPDATE_PRODUCTS_REQUEST = 'UPDATE_PRODUCTS_REQUEST'
export const UPDATE_PRODUCTS_SUCCESS = 'UPDATE_PRODUCTS_SUCCESS'
export const UPDATE_PRODUCTS_FAIL = 'UPDATE_PRODUCTS_FAIL'
export const UPDATE_PRODUCTS_RESET = 'UPDATE_PRODUCTS_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'